### ISSUE TITLE
‘cozy-light install-distro personal-cloud‘ fails: `Cannot find module 'internal/fs'`?

### ISSUE THREAD

**Issue by fasiha** [cozy-labs/cozy-light#88]
Did a fresh install of Node 7.1 on macOS from download at nodejs.org. All my other node projects work fine, but cozy-light install-distro fails, in the same manner as nodejs/node/issues/9377 — asking here: has anyone else experienced this for cozy-light and/or found a workaround?

```
➜  node -v
v7.1.0
➜  npm -v
3.10.9
➜  sudo npm install -g cozy-light
Password:
/usr/local/bin/cozy-light -> /usr/local/lib/node_modules/cozy-light/bin/cozy-light
/usr/local/lib
└── cozy-light@0.4.9
➜ cozy-light install-distro personal-cloud
module.js:474
    throw err;
    ^

Error: Cannot find module 'internal/fs'
    at Function.Module._resolveFilename (module.js:472:15)
    at Function.Module._load (module.js:420:25)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at evalmachine.<anonymous>:17:20
    at Object.<anonymous> (/usr/local/lib/node_modules/cozy-light/node_modules/npm/node_modules/npm-registry-client/node_modules/graceful-fs/fs.js:11:1)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
```

**Comment by clochix** [comment]
Hello @fasiha,

Pinging @frankrousseau but I fear the Cozy-light project may be considered dead.
At the time we last worked on it, we were still using Node 0.10, some dependencies are probably not compatibles with Node 7.

Sorry for the inconvenience :-S

**Comment by frankrousseau** [comment]
Yep @fasiha, I don't work at Cozy anymore and I was the one who was experimenting with it. But if you are interested in playing with it I can help you.

**Comment by fasiha** [comment]
Thanks, I’ll post here when I look into this again!
